### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by jalovisko** [JustinSDK/cqMore#2]
When I attempt to import cqmore, I get the following error:
```
>>> import cqmore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jalovisko/anaconda3/envs/cqgui/lib/python3.8/site-packages/cqmore/__init__.py", line 1, in <module>
    from ._plugin import Workplane
  File "/home/jalovisko/anaconda3/envs/cqgui/lib/python3.8/site-packages/cqmore/_plugin.py", line 7, in <module>
    from ._typing import FaceIndices, MeshGrid
  File "/home/jalovisko/anaconda3/envs/cqgui/lib/python3.8/site-packages/cqmore/_typing.py", line 5, in <module>
    Point2D = tuple[float, float]
TypeError: 'type' object is not subscriptable
```
I feel like the issue is that instead of `tuple` there should be `Tuple` which in turn should be imported from `typing`. Might be wrong though.

**Comment by jalovisko** [comment]
Yes, I managed to fix it by importing and replacing `tuple` and `list` in several places. I am not sure I am the only one with the issue but I will make a pull request with the changes shortly if it is ever needed.

**Comment by jalovisko** [comment]
The pull request is mentioned above. Let me know if anything! :)

**Comment by JustinSDK** [comment]
Please upgrade to Python 3.9 which supports "PEP 585 – Type Hinting Generics In Standard Collections".
https://docs.python.org/3/whatsnew/3.9.html
